"""
Write the mixed-signal deck: the RTL (build/mixed/radio_digital.so, from
sim/mixed/build_so.sh) as an XSPICE d_cosim instance, closing the comparator
trim servo through the real analog:

    det (PWL from sim/rx/gen_det.py) -> lpf_rc -> avg_sc (sc_phi1/2 from the
    RTL) -> comp_ct (trim = r2r(trim_out[7:0] from the RTL) + 1 pF) -> comp_in

The d_cosim port list is GENERATED from the inputs.h / outputs.h of the same
build (header order, each bus MSB first, as verilator_shim.cpp maps them), so
it can't drift from the .so. Every bit gets its own node name, e.g.
trim_out_7 .. trim_out_0. The analysis (plot_mixed.py) then checks the bus
order end to end: v(trim) must be exactly code / 256 x 1.8 V, with the code
starting at 128 and moving one LSB per servo step.

Digital stimulus: RX role, code 0x5A (the burst gen_det.py makes), no straps;
clk 10 MHz (d_osc); rst_n low for the first 2 us.

    python sim/mixed/gen_mixed.py <level> [tstop]     e.g. -70 15.2m
    then in the osic image from build/mixed:  ngspice -b mixed_<level>.cir
"""
import os
import re
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))
OUT = os.path.join(ROOT, 'build', 'mixed')
OBJ = os.path.join(OUT, 'radio_digital_obj_dir')
CODE = 0x5A
SUBCKTS = ('lpf_rc', 'avg_sc', 'comp_ct', 'r2r')


def ports(header):
    """[(name, msb, lsb)] in the order verilator_shim.cpp walks them."""
    rx = re.compile(r'VL_DATA\(\d+,(\w+),(\d+),(\d+)\)')
    return [(m[1], int(m[2]), int(m[3])) for m in rx.finditer(open(os.path.join(OBJ, header)).read())]


def bits(plist):
    """Node names, MSB first per bus: trim_out_7 ... trim_out_0; scalars as is."""
    out = []
    for name, msb, lsb in plist:
        out += [name] if msb == lsb == 0 else [f'{name}_{i}' for i in range(msb, lsb - 1, -1)]
    return out


def subckts():
    src = open(os.path.join(ROOT, 'build', 'real', 'tb_radio_analog.spice')).read().split('\n')
    keep, on = [], False
    for ln in src:
        t = ln.split()
        if t and t[0].lower() == '.subckt' and t[1] in SUBCKTS:
            on = True
        if on:
            keep.append(ln)
        if on and t and t[0].lower() == '.ends':
            on = False
            keep.append('')
    return '\n'.join(keep)


def main(level, tstop):
    ins, outs = bits(ports('inputs.h')), bits(ports('outputs.h'))
    # constant digital inputs: RX (ui_in[7] = 0), code 0x5A on ui_in[6:0], uio_in = 0
    const = {f'ui_in_{i}': (CODE >> i) & 1 for i in range(7)}
    const['ui_in_7'] = 0
    const.update({f'uio_in_{i}': 0 for i in range(8)})
    assert set(ins) == {'clk', 'rst_n', 'comp_in'} | set(const), f'unexpected inputs {ins}'
    for need in ['trim_out_0', 'trim_out_7', 'sc_phi1', 'sc_phi2', 'rx_en', 'uio_out_4', 'uo_out_7']:
        assert need in outs, need
    to_analog = [f'trim_out_{i}' for i in range(8)] + ['sc_phi1', 'sc_phi2', 'rx_en', 'uio_out_4', 'uo_out_7'] + \
                [f'uo_out_{i}' for i in range(7)]
    L = [f'* mixed-signal trim servo, det {level} dBm (generated by sim/mixed/gen_mixed.py)',
         '.lib /foss/pdks/sky130A/libs.tech/combined/sky130.lib.spice tt',
         subckts(),
         f'.include ../det_{level}.inc',
         '* ---- digital: the RTL. Port list generated from inputs.h / outputs.h (MSB first per bus)',
         f'adut [ {" ".join(ins)} ] [ {" ".join(outs)} ] null dut',
         '.model dut d_cosim simulation="./radio_digital.so"',
         'aclk 0 clk clock',
         '.model clock d_osc cntl_array=[-1 1] freq_array=[10Meg 10Meg]',
         '* constant inputs and reset, analog -> digital',
         '.model a2d adc_bridge(in_low=0.6 in_high=1.2)',
         '.model d2a dac_bridge(out_low=0 out_high=1.8 t_rise=1n t_fall=1n)',
         'Vrst rst_a 0 pwl(0 0 2u 0 2.001u 1.8)',
         'arst [rst_a] [rst_n] a2d']
    for n, v in sorted(const.items()):
        L += [f'V{n} {n}_a 0 {1.8 if v else 0}', f'a{n} [{n}_a] [{n}] a2d']
    L += ['acomp [comp] [comp_in] a2d', '* outputs used by the analog (and for plots), digital -> analog']
    L += [f'a{n} [{n}] [{n}_a] d2a' for n in to_analog]
    L += ['* ---- analog: as radio_analog (lpf, averager, comparator, trim DAC), comparator bias ideal',
          'VDD VDD 0 1.8',
          'Ibc VDD ibc 1u',
          'x11 det lpf 0 lpf_rc',
          'x12 lpf sc_phi1_a sc_phi2_a avg VDD 0 avg_sc',
          'x13 avg lpf trim ibc comp VDD 0 comp_ct',          # symbol defaults, as in radio_analog
          'xdac ' + ' '.join(f'trim_out_{i}_a' for i in range(8)) + ' trim 0 r2r',
          'Ctrim trim 0 1p',
          '.ic v(avg)=1.438 v(x12.cs)=1.438 v(lpf)=1.438',
          '.save v(det) v(lpf) v(avg) v(comp) v(trim) v(rx_en_a) v(uio_out_4_a) v(uo_out_7_a) v(sc_phi1_a) '
          + ' '.join(f'v(uo_out_{i}_a)' for i in range(7)),
          '.options method=GEAR',
          '.control',
          f'tran 0.1u {tstop} 0 0.2u',
          f'write mixed_{level}.raw',
          '.endc', '.end']
    path = os.path.join(OUT, f'mixed_{level}.cir')
    with open(path, 'w') as fh:
        fh.write('\n'.join(L) + '\n')
    print('wrote', path, '\n inputs :', ' '.join(ins), '\n outputs:', ' '.join(outs))


if __name__ == '__main__':
    main(int(sys.argv[1]), sys.argv[2] if len(sys.argv) > 2 else '15.2m')
