"""Write layout/README.md: a table of every layout/*.gds with a TT GDS viewer link
(works once the file is pushed to github main) and its size (top cell bbox, KLayout).

    ~/work/asic-workshop/venv/bin/python tools/gds_links.py      (needs the klayout module)
"""
import glob
import os

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
RAW = 'https://raw.githubusercontent.com/mattvenn/ook-asic-radio/main/layout/'
VIEW = 'https://gds-viewer.tinytapeout.com/?url='


def bbox_um(path):
    """Top cell bounding box (um). The raw XY scan this replaced mixed subcell-local
    coordinates into hierarchical GDS (r2r read 80 um tall instead of 54)."""
    import klayout.db as kdb
    ly = kdb.Layout()
    ly.read(path)
    b = ly.top_cell().dbbox()
    return b.width(), b.height()


def main():
    rows = []
    for g in sorted(glob.glob(os.path.join(ROOT, 'layout', '*.gds'))):
        name = os.path.basename(g)
        w, h = bbox_um(g)
        rows.append(f'| `{name[:-4]}` | {w:.1f} × {h:.1f} µm ({w * h:,.0f} µm²) | '
                    f'[view]({VIEW}{RAW}{name}) | `layout/gen/` |')
    with open(os.path.join(ROOT, 'layout', 'README.md'), 'w') as fh:
        fh.write('# Block layouts\n\n'
                 'Generated by `layout/gen/<block>.py` (KLayout + sky130 pcells); flow and checklist in '
                 '`docs/layout.md`.\nViewer links work once the GDS is pushed to `main`. '
                 'This table is written by `tools/gds_links.py`.\n\n'
                 '| block | size (incl. shape overhang) | preview | source |\n|---|---|---|---|\n' +
                 '\n'.join(rows) + '\n')
    print('\n'.join(rows))


if __name__ == '__main__':
    main()
